### ISSUE TITLE
Fingerpaint not working on Manjaro Gnome Wayland

### ISSUE THREAD

**Issue by hahihohehe** [Wazzaps/fingerpaint#12]
I'm using Manjaro Gnome with Wayland and installed the fingerpaint-wayland aur.

When I use the following command: `fingerpaint - o test.png`
I get the following output:

Using touchpad: SynPS/2 Synaptics TouchPad
Unexpected touchpad state: "", are you using Gnome?

**Comment by Wazzaps** [comment]
That's weird, try this:
`dconf write /org/gnome/desktop/peripherals/touchpad/send-events '"enabled"'`

**Comment by hahihohehe** [comment]
Thank you, after executing that command it works fine.

**Comment by Wazzaps** [comment]
Seems like new GNOME doesn't set this (or it's an Arch quirk).
I'll probably need to fix this.

**Comment by Skaldebane** [comment]
Same here, still same issue with Fedora 35 with GNOME 41.4.
The command above fixes it.

Tested on fingerpaint 1.2.2 installed from pip3.

**Comment by Wazzaps** [comment]
I'll fix this later today then

**Comment by Skaldebane** [comment]
Hi there! No updates on this?

**Comment by Wazzaps** [comment]
Sorry for the delay!

https://github.com/Wazzaps/fingerpaint/releases/tag/v1.2.3 should fix this.

**Comment by Skaldebane** [comment]
Thanks a lot! I'll give it a shot.

**Comment by alibillalhammoud** [comment]
Just wanted to update...on fedora version 1.2.6 works after running as Wazzaps said
`dconf write /org/gnome/desktop/peripherals/touchpad/send-events '"enabled"'`

**Comment by Wazzaps** [comment]
> Just wanted to update...on fedora version 1.2.6 works after running as Wazzaps said `dconf write /org/gnome/desktop/peripherals/touchpad/send-events '"enabled"'`

What is the output if you don't do this? (Roughly)

**Comment by alibillalhammoud** [comment]
> > Just wanted to update...on fedora version 1.2.6 works after running as Wazzaps said `dconf write /org/gnome/desktop/peripherals/touchpad/send-events '"enabled"'`
> 
> 
> 
> What is the output if you don't do this? (Roughly)

It was 
Unexpected touchpad state: "", are you using Gnome?

**Comment by Wazzaps** [comment]
Fixed by [v1.2.7](https://github.com/Wazzaps/fingerpaint/releases/tag/v1.2.7), also available with `pip install -U fingerpaint`
