### ISSUE TITLE
ability to go fullscreen

### ISSUE THREAD

**Issue by Bhupesh-V** [Wazzaps/fingerpaint#15]
right now fingerpaint opens up in small windows which is sort of limited in visual sense when we want to doodle. 
It would be nice to have a maximize window option

**Comment by Wazzaps** [comment]
Added it with the new v1.2.4 release, it's already on pip and the [Github release](https://github.com/Wazzaps/fingerpaint/releases/tag/v1.2.4).

If you found this utility useful make sure to tell me or send me a cool doodle :)

**Comment by Vaisakhkm2625** [comment]
Sorry for commenting on a closed post
fullscreen option is only showing  input at top corner of the canvas

![image](https://github.com/Wazzaps/fingerpaint/assets/68694876/a688fd99-e35f-4d15-ae2c-8d13188e7697)

**Comment by Wazzaps** [comment]
All good :)
Could you describe your environment? Distro version? GNOME/KDE/something else?
Also would be nice to open an issue so I can keep track of your issue specifically :)

Also, is your touchpad actually square or is that a bug?

**Comment by Vaisakhkm2625** [comment]
> All good :) Could you describe your environment? Distro version? GNOME/KDE/something else? Also would be nice to open an issue so I can keep track of your issue specifically :)
> 
> Also, is your touchpad actually square or is that a bug?

sure....
i am on kde, and touchpad is not square... it's a bug and it is like that only when we go full screen
i will raise a new issue
