### ISSUE TITLE
Release Tag (v1.1)

### ISSUE THREAD

**Issue by jhossbach** [Wazzaps/fingerpaint#2]
Hey there, it might be a good idea to create a version tag / release for the package. I can pick up from there and create an AUR package.

_Originally posted by @jhossbach in https://github.com/Wazzaps/fingerpaint/discussions/1#discussioncomment-1142541_

**Comment by Wazzaps** [comment]
That would be awesome! I made a release [here](https://github.com/Wazzaps/fingerpaint/releases/tag/v1.1.2), feel free to package it :D
