### ISSUE TITLE
Create a Snap package (once Fingerpaint has a save UI)

### ISSUE THREAD

**Issue by heidiwenger** [Wazzaps/fingerpaint#20]
For an easy installation, clicking Install at Snap Store in Ubuntu, which is the first Linux distro for many new users now coming to Linux. Solus, KDE Neon, Manjaro, MakuluLinux, Ubuntu MATE, Zorin OS etc. support snapd by default too.

Request was put up originally to here: https://forum.snapcraft.io/t/fingerpaint-draw-with-touchpad-or-sign-a-signature-easily-only-non-beginner-friendly-installation-available/31234

**Comment by Wazzaps** [comment]
Idea (Not working on this just yet): Wrap it in a bash script with a `yad` wrapper for the save function.
Do we even have access to /dev/input* from snap? does it have to be a "classic" snap?

**Comment by Wazzaps** [comment]
Published a snap, will close once the required interfaces are auto-connected by default (requires Cannonical's approval)

**Comment by heidiwenger** [comment]
> Published a snap, will close once the required interfaces are auto-connected by default (requires Cannonical's approval)

Much appreciated. I hope it won't be too long for the approval.

**Comment by Wazzaps** [comment]
It's been published, now also featuring a new GTK-based UI: https://snapcraft.io/fingerpaint
