### ISSUE TITLE
State of Wayland support

### ISSUE THREAD

**Issue by jhossbach** [Wazzaps/fingerpaint#21]
I am wondering whether Wayland is supported now, is `xinput` still needed?
There was an issue on the AUR: https://aur.archlinux.org/packages/fingerpaint-wayland

https://github.com/Wazzaps/fingerpaint/blob/12b865681dbe4b5602bc052e9f6dd7d515554952/fingerpaint/fingerpaint.py#L298-L305

**Comment by Wazzaps** [comment]
Wayland is supported on Gnome (PRs welcome for other compositors), this is a relic of when it didn't support Wayland.
I'll look at this once I get access to a computer (~2 days)

**Comment by Wazzaps** [comment]
Fixed with [v1.2.5](https://github.com/Wazzaps/fingerpaint/releases/tag/v1.2.5).
Could you update the PKGBUILD? :)
