### ISSUE TITLE
Loosen dependencies

### ISSUE THREAD

**Issue by jhossbach** [Wazzaps/fingerpaint#3]
Tightening the dependencies in your `setup.py` makes it hard for some packaging managers (`pacman`) to install the package. It is also not necessary to keep a specific version. I tested it using the newer version `Pillow v8.3.1`

Also, (for me at least) there seems to be some issue with the Arch package `python-pyudev` giving the wrong version which also messes with this requirement.

Feel free to just cherry-pick from https://github.com/jhossbach/fingerpaint/commit/9afe96d339f59353a4e7b4b22353e9ca331c2074.

**Comment by Wazzaps** [comment]
Fixed with commit 0a2e45d62b8ec87992b20a6ce2e21b921bf6a3a2, thanks
