### ISSUE TITLE
`99-touchpad-access.rules` not found

### ISSUE THREAD

**Issue by ZXTube** [Wazzaps/fingerpaint#36]
```
[user@nixos:~/Documents]$ fingerpaint -o test.png 
Using touchpad: DELL096A:00 04F3:30C4 Touchpad
Failed to access touchpad!
Touchpad access is currently restricted. Would you like to unrestrict it?
[Yes]/no: yes
/nix/store/lwm6h0jr8w73n7gz7lxf4cmfdx59b51k-fingerpaint-1.2.7/lib/python3.10/site-packages/fingerpaint/data/fix_permissions.sh: line 3: /etc/udev/rules.d/99-touchpad-access.rules: Read-only file system
```

I'm using NixOS 23.11 and GNOME.

Thanks in advance

**Comment by Wazzaps** [comment]
According to [this answer](https://discourse.nixos.org/t/creating-a-custom-udev-rule/14569/2), you can add the required rule to your nix configuration like so:
```nix
services.udev.extraRules = ''
    ENV{ID_INPUT_TOUCHPAD}=="1", MODE="0664"
'';
```
Afterwards you can run:
- `sudo nixos-rebuild switch` (I'm pretty sure this is the command, I don't use nixos)
- `sudo udevadm control --reload-rules`
- `sudo udevadm trigger`

and it should work.
